name: Continuous Integration

on:
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-13
          - ubuntu-22.04
          - windows-2022
    name: "Build ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.12.0"
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@v1.1
        with:
          version: "1.11.1"
      - name: Install Meson
        run: python3 -m pip install meson==1.2.1
      - name: Configure project
        run: meson setup build/
      - name: Check formatting
        if: ${{ runner.os == 'Linux' }}
        run: ninja -C build/ clang-format-check
      - name: Build project
        run: ninja -C build/
